#!groovy
timestamps {
    properties([gitLabConnection(ciproperties.getGitlab().URL)])
    library ciproperties.getGitlab().URL + ciproperties.getGitlab().Main_Pipeline_Libs_Branch
    
    nodeTemplates."dind" {
        stage('Checkout') {
            checkout scm
        }

        stage('Build & Push Docker image') {
            dockerProject.Build()
        }
    }
}